import { StyleSheet } from "react-native";
export const colors = {
  background: "#F4F7FC",
  ink: "#17243B",
  muted: "#627189",
  brand: "#285AE8",
  border: "#DCE3EF",
  danger: "#B42335",
};
export const global = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  content: {
    padding: 22,
    gap: 16,
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
  },
  card: {
    backgroundColor: "#FFFFFF",
    padding: 22,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 14,
  },
  title: { fontSize: 30, fontWeight: "700", color: colors.ink },
  subtitle: { fontSize: 15, lineHeight: 22, color: colors.muted },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.ink,
    marginBottom: 7,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#FFFFFF",
    padding: 14,
    borderRadius: 11,
    fontSize: 16,
    color: colors.ink,
  },
  button: {
    minHeight: 48,
    paddingVertical: 13,
    paddingHorizontal: 18,
    backgroundColor: colors.brand,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: { color: "#FFFFFF", fontWeight: "700", fontSize: 15 },
  secondary: { backgroundColor: "#E9EEFB" },
  secondaryText: { color: colors.brand },
  error: {
    color: colors.danger,
    backgroundColor: "#FFF0F1",
    padding: 12,
    borderRadius: 10,
    fontSize: 14,
    lineHeight: 20,
  },
  row: { flexDirection: "row", alignItems: "center", gap: 12 },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 16,
    padding: 24,
  },
});
